2018-06-29 14:19:56,415 - index.py[line:851] - ERROR: É¾³ý×Ó½Úµã:UnboundLocalError("local variable 'stage_id' referenced before assignment",)
